---



---



---



---

spring.application.name: parking-management-system
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms
    username: user
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  exposed:
    show-sql: true
    generate-ddl: true
